# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Worflow
on:
  push:
    branches: 
      - '*'         
      - '*/*'       
      - '**'        
      - '!main'   
  pull_request:
    branches: 
      - "main" 

jobs:
  tests:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with: 
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./Parameters.Test.Unit/
    - name: Build
      run: dotnet build --no-restore ./Parameters.Test.Unit/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Parameters.Test.Unit/

  build:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with: 
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./Parameters.sln
    - name: Build
      run: dotnet build --no-restore ./Parameters.sln
      
  pull-request:
    runs-on: ubuntu-latest
    needs: [tests, build]
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      
      - name: Running on a pull request branch
        if: steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Create pull request ${{ steps.branch-name.outputs.current_branch }} into dev
          signoff: false
          branch: ${{steps.branch-name.outputs.current_branch}}
          base: homolog
          title: Create pull request ${{ steps.branch-name.outputs.current_branch }}
          body: |
            Create pull request
            - Updated with *today's* date
            - Auto-generated [create-pull-request][1]
          labels: |
            report
            automated pr
          assignees: gustavo-pavan
          reviewers: gustavo-pavan
