version: '3.4'

services:
# api
  parameter-api:
    container_name: parameter-api
    image: ${DOCKER_REGISTRY-}parameterspresentationapi
    build:
      context: .
      dockerfile: Parameters.Presentation.Api/Dockerfile
    networks:
      - parameter-network
    environment:
      - MongoSettings_Connection=mongodb://root:password123@mongodb:27017
      - MongoSettings_DatabaseName=PARAMETERS
    depends_on:
        - mongodb
    links:
        - mongodb

# database
  mongodb:
    container_name: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_DATABASE: BANK_ACCOUNT
    ports:
      - 27017:27017
    volumes:
      - ./Volumes/MongoDB:/data/db
    networks:
      - parameter-network

# database management
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      -  mongodb
    links:
      - mongodb
    networks:
      - parameter-network


networks: 
    parameter-network:
      driver: bridge