version: '3.4'
services:
  parameter-api:
    container_name: parameter-api
    image: '${DOCKER_REGISTRY-}parameterspresentationapi'
    build:
      context: .
      dockerfile: Parameters.Presentation.Api/Dockerfile
    networks:
      - parameter-network
    environment:
      - MongoSettings_Connection=mongodb://root:password123@mongodb:27017
      - MongoSettings_DatabaseName=PARAMETERS
      - ConnectionStrings_Integration=Server=mssqldb,1433;Initial Catalog=Parameter;Persist Security Info=False;User ID=sa;Password=mssql1Ipw;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;
      - RabbitMQConfiguration:HostName=rabbitmq
      - RabbitMQConfiguration:UserName=mqadmin
      - RabbitMQConfiguration:Password=rmbt1L2
      - RabbitMQConfiguration:RetryCount=2
      - RabbitMQConfiguration:TYPE_EXCHANGE=direct
      - RabbitMQConfiguration:BROKER_NAME=flow_broker
      - RabbitMQConfiguration:QUEUE_NAME=parameter_mqueue
    depends_on:
      - mongodb
      - mssqldb
      - rabbitmq
    links:
      - mongodb
      - mssqldb
      - rabbitmq

  mongodb:
    container_name: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_DATABASE: BANK_ACCOUNT
    ports:
      - '27017:27017'
    volumes:
      - './Volumes/MongoDB:/data/db'
    networks:
      - parameter-network

  mssqldb:
     image: 'mcr.microsoft.com/mssql/server:2019-latest'
     container_name: mssql
     ports:
       - '1433:1433'
     volumes:
       - './Volumes/mssql/data/:/var/lib/mssqlql/data'
     environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=mssql1Ipw
     networks:
       - parameter-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
       - 5672:5672
       - 15672:15672
    environment:
       - RABBITMQ_DEFAULT_USER=mqadmin
       - RABBITMQ_DEFAULT_PASS=rmbt1L2
    volumes:
       - ./Volumes/rabbitmq/data/:/var/lib/rabbitmq
       - ./Volumes/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - parameter-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      -  mongodb
    links:
      - mongodb
    networks:
      - parameter-network

networks:
  parameter-network:
    driver: bridge
