# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

jobs:
  # tests:
  #   runs-on: ubuntu-latest
    
    # steps:
  #   - uses: actions/checkout@v3
  #   - name: Setup .NET Core SDK
  #     uses: actions/setup-dotnet@v3.0.3
  #     with: 
  #       dotnet-version: 7.0.102
  #   - name: Restore dependencies
  #     run: dotnet restore ./Parameters.Test.Unit/
  #   - name: Build
  #     run: dotnet build --no-restore ./Parameters.Test.Unit/
  #   - name: Test
  #     run: dotnet test --no-build --verbosity normal ./Parameters.Test.Unit/

  # build:
  #   runs-on: ubuntu-latest
  #   needs: [tests]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Setup .NET Core SDK
  #     uses: actions/setup-dotnet@v3.0.3
  #     with: 
  #       dotnet-version: 7.0.102
  #   - name: Restore dependencies
  #     run: dotnet restore ./Parameters.sln
  #   - name: Build
  #     run: dotnet build --no-restore ./Parameters.sln
  #   - name: Test
  #     run: dotnet test --no-build --verbosity normal ./Parameters.sln
      
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          # token: ${{ secrets.PAT }}
          commit-message: Update report
          signoff: false
          branch: example-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
          labels: |
            report
            automated pr
          assignees: gustavo
          reviewers: gustavo
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: false
